name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up C (C environment)
        uses: actions/setup-cpp@v2
        with:
          compiler: gcc
          cxx-standard: 99

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind build-essential
  

      - name: Build
        run: make

      - name: Run Tests
        run: make test

      - name: Run valgrind
        run: make valgrind_test
        continue-on-error: true